version: "3.8"
services:
  app:
    build: ..
    ports:
      - "8080:8080"
      - "2112:2112"
    depends_on:
      - db
      - prometheus
    restart: unless-stopped
    volumes:
      - ./.env:/.env
      - ./config.yml:/config.yml
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: location
  docs:
    image: redocly/redoc
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      SPEC_URL: swagger/swagger.yaml
    volumes:
      - ./docs/:/usr/share/nginx/html/swagger/
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
