version: "3.8"
services:
  app:
    image: local/location
    ports:
      - "8080:8080"
      - "2112:2112"
    depends_on:
      - db
      - prometheus
    restart: unless-stopped
    env_file:
     - ./.env
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: location
  docs:
    image: redocly/redoc
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      SPEC_URL: swagger/swagger.yaml
    volumes:
      - ../../api/:/usr/share/nginx/html/swagger/
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
