name: 'Location: Build'

on:
  push:
    paths:
      - 'services/location/**'
  pull_request:
    paths:
      - 'services/location/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: make build

    - name: Test
      run: make tests

    - name: Install swag Go package
      run: go get -u github.com/swaggo/swag/cmd/swag

    - name: Build docs
      run: make docs

    - name: Commit docs changes
      uses: EndBug/add-and-commit@v7
      with:
        cwd: './services/location'
        add: 'docs'
        message: 'Update location service docs'

defaults:
  run:
    shell: bash
    working-directory: services/location
