name: Lint Location Service

on:
  push:
    paths:
      - 'services/location/**'
  pull_request:
    paths:
      - 'services/location/**'

jobs:
  lint:
    name: Lint Location service code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.35
          working-directory: './services/location'
