name: 'Location Service'

on:
  push:
    paths:
      - 'services/location/**'
  pull_request:
    paths:
      - 'services/location/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download dependencies
        run: go mod vendor
      - name: Test
        run: make test
      - name: Build app and container
        run: make container
      - name: Commit docs changes
        uses: EndBug/add-and-commit@v7
        with:
          cwd: './services/location'
          add: 'api'
          message: 'location: update HTTP API docs'
          author_name: Emeric de Bernis
          author_email: emeric.debernis@gmail.com

  push:
    needs: build
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/master') || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download dependencies
        run: go mod vendor
      - name: Login to Github Registry
        shell: bash
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        run: echo "$CR_PAT" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin
      - name: Make container and push images
        shell: bash
        env:
          REGISTRY: ghcr.io/${GITHUB_REPOSITORY}
        run: make push

defaults:
  run:
    shell: bash
    working-directory: services/location
